### ISSUE TITLE
tentative roadmap

### ISSUE THREAD

**Issue by Geal** [CleverCloud/biscuit#12]
there's already been a lot of discussion around what the biscuit can be and how it could work, so it's probably a good time to sum things up and see what's needed.

## Semantics

With #6 and #8, along with some out of band discussions, we have a better idea of how attenuation should work:
- the first caveat specifies an *authority* field indicating the basic rights for this token, out of a set of rights the verifier knows about
- some of those rights can be marked as *critical*, and the verifier should refuse a token that does not put bounds on it (to allow accidental elevation of rights)
- there's an *ambient authority* with information coming from the context, ie which resource is accessed, current time, source IP address, etc
- the verifier also provides information from its own context (different verifiers might care about different rights or resources, etc)
- each caveat checks that the request is within what it authorizes (resource accessed, kind of operation...)

## Caveat language

We're evaluating a [datalog](https://en.wikipedia.org/wiki/Datalog) like language to express the caveats. It is simple to implement and allows complex queries. It can also be used to generate the `authority` field in a compact way.

We have been exploring [example queries](https://github.com/CleverCloud/biscuit/issues/11) to get a feel for how it could work.

### Asymmetric mode

We need to support our goals of a token that can be attenuated offline and verified in a decentralized way. To that end, we explored [a few cryptographic systems](https://github.com/CleverCloud/biscuit/pull/10):
- first one is an aggregated signature scheme using pairing based cryptography on BLS curves. Easy to follow and very compact, but verification can be quite slow, and very few good libraries are available
- second one is an aggregated zero knowledge discrete log proof using verifiable random functions. Quite fast and there's a version that does not add too much size overhead
- third one uses a PKI like system with a challenge/response to authenticate the last element of the chain (its properties are a little bit different than the others)

All three of them would be usable, but we will need an audit of the schemes before deciding which one to go with.

### Symmetric mode

It would be useful to have an alternative mode to [transform a biscuit token to a symmetric construction](https://github.com/CleverCloud/biscuit/issues/7), a bit like macaroons.
That mode is not well defined yet, but the idea would be to send an asymmetric token to the authentication service, which will check the token and its caveats, and create a new token with the same caveats, but using a symmetric mode, possibly with encryption.
At the cost of one RTT, we get a token that is much faster to check and can be fixed for requests to only one service (the one who knows the secret key).

# Roadmap

To get to a usable token implementation, here's what we would need now:
- [ ] credential language
  - [x] example queries
  - [ ] example implementation of datalog with constraints
  - [ ] defining an API over the language, to allow easier, higher level usage
  - [ ] write a specification for the types and behaviour
- [ ] semantics
  - [x] define the expected behaviour
  - [ ] define the authority and caveats behaviour in terms of the credential language
  - [ ] write a specification for the semantics
- [ ] cryptography
  - [ ] asymmetric mode
    - [x] propose some usable schemes
    - [x] experimental implementation
    - [x] benchmarks (speed for attenuation and verification, size overhead)
    - [ ] audit the three schemes
    - [ ] choose one of the schemes
    - [ ] check how easy it is to implement it in various languages (availability of high quality libraries, serialization, etc)
    - [ ] write a specification for the cryptography primitives we will use
  - [ ] symmetric mode
    - [ ] propose some usable schemes
    - [ ] experimental implementation
    - [ ] benchmarks 
    - [ ] audit
    - [ ] choose one of the schemes
    - [ ] write a specification for the cryptography primitives we will use
- [ ] serialization
  - [ ] define a format to store the credential language and its basic types
  - [ ] define a binary format for the asymmetric token, with its blocks and signature(s)
  - [ ] define a binary format for the symmetric token
  - [ ] define a way to store the token in text formats (base64 of the binary token, etc)
- [ ] tooling
  - [ ] define a common API to create a token, attenuate it and verify it (important point: usable error messages)
  - [ ] pretty printing of the token, and especially its logic language (will be useful for debug, in web inspectors and such)
  - [ ] example implementations
    - [ ] first one will probably be in Rust
    - [ ] Java implementation?
    - [ ] Web Assembly + Javascript for demos like https://jwt.io/

**Comment by Geal** [comment]
updated following the 2.0 merge #77

**Comment by CMCDragonkai** [comment]
Has there been any update since 3.0?

**Comment by divarvel** [comment]
I have updated the roadmap. For a tl;dr:

- for go and java, the current objective is to support v4 blocks (check all, third-party blocks)
- as for the spec itself,
  - there is work on supporting specific EcDSA profiles in addition to ed25519, and integration with webauthn
  - we are starting to think about new datalog features that would warrant a new block version
- there is still work to be done on documentation and use cases / experience reports

**Comment by divarvel** [comment]
don't hesitate to reach out if you have ideas / questions
