### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by Geal** [CleverCloud/biscuit#57]
Biscuit has been in development for [2 years now](https://github.com/CleverCloud/biscuit/commit/59a07432e7707bbc85efc366709e56f3a0cc988b) and is now used in production. Most of the [initial roadmap](https://github.com/CleverCloud/biscuit/issues/12) is done (we still need to commission an audit).

So it will soon be time for a stable release and more public communication. Before that, I'd prefer that we clean things up a bit, there are design decisions that were left alone because fixing them would be breaking changes, but a 1.0 release would be the right time to take care of them (here I consider a breaking change anything that would invalidate how currently existing tokens would be validated).

This will be a meta issue for the work needed towards the major release:
- vocabulary issues:
  - [x] #23 Consider renaming larger
  - [x] #24 Consider renaming In/NotIn
  - [x] #52 renaming atom (not a breaking change, this would mainly change the API in libraries)
- [x] #54 text syntax changes (changes to the parser and printer)
- [x] #63 renaming In to Contains, removing NotIn
- [x] #55 Protobuf schema simplification
- [x] #59 adding a version field to the Protobuf format
- [x] #1 revocation identifiers
- new data types. There might be more of them we could add. I'd also like to consider whether constraints could be folded in the expression type (by making boolean expressions)
  - [x] #51 new atom type: set 
  - [x] #38 new atom type: expression
  - [x] #61 new type: boolean
  - [x] #62 "deny" caveats vs "success caveats"
- Datalog evaluation:
  - [ ] #50 specifying the regular expression features
  - [x] #47 allowing variables in constraints (need to decide if we allow it or not)
  - [x] #53 explicit run time limits for the datalog engine
  - [ ] #58 Using the symbol table for strings too
  - [ ] #56 Datalog restrictions in blocks

I'll make a branch of this repo with updated test samples once I've started that work on the Rust library.

see anything else we would need?
cc @divarvel @daeMOn63 @titanous @Keruspe @KannarFr @BlackYoup @meh

**Comment by Geal** [comment]
I'm starting the work in the 1.0 branch: https://github.com/CleverCloud/biscuit/tree/1.0
The samples directory will contain the samples generated at version 0 of the format in a `v0/*` subdirectory, while tokens generated with the new format and features will be in the `v1/` folder, so we can test that new implementations also accept older tokens. I'll try to make one commit per feature to make it easier to update the implementations gradually.

**Comment by Geal** [comment]
The first example of handling multiple versions is done with #23 in the Rust version: https://github.com/CleverCloud/biscuit-rust/commit/01f1ba0f9a32304a68a3fe67d667d50d4eafff50 (spec: https://github.com/CleverCloud/biscuit/commit/456549d82a59904783198711d4f405fa6c897ffc )

* new tokens generated with a schema at version 1 cannot be deserialized with the 0.9 release of the Rust library.
* new tokens generated with a schema at version 1 can be deserialized by the 1.0 branch of the Rust library
* old tokens generated with a schema at version 0 can be deserialized by the 1.0 branch, and it will convert it to its renamed types

This is a small change for now, renaming fields does not modify the structure significantly (the generated tokens are the same byte for byte)

**Comment by Geal** [comment]
Next, changing the protobuf format to use `oneof` (#55) in Rust: https://github.com/CleverCloud/biscuit-rust/commit/7a84336f9bbfd3541d209a954a85b37563e51ad9 (spec: https://github.com/CleverCloud/biscuit/commit/0ec07df89dc12167ec93ff0abec1228cb99416b1 )

this changes the token's format, but not internal structures in the library, so there's no change to the feature set

**Comment by Geal** [comment]
Adding support for boolean type (#61):
spec: 0954e32
Rust: CleverCloud/biscuit-rust@78a7657

**Comment by Geal** [comment]
Adding support for the set type (#51):
spec: f5169d2
Rust: CleverCloud/biscuit-rust@bb47508

**Comment by meh** [comment]
Any chance of getting `.` as allowed character for names in the language? At the moment I'm using the functional API for building caveats and rules but it gets very hairy very quickly.

**Comment by Geal** [comment]
@meh possible, but I'll have to check if it will be compatible with expressions. I'm planning more operations like `string.len()` etc

**Comment by meh** [comment]
Yeah that's why I didn't just go for it, I know it's a valuable symbol for extending the language. 

For me it doesn't have to be a dot either, I just want an additional separator to _ so I can namespace things a bit, : would also work.

**Comment by Geal** [comment]
Expressions(#38):
spec: https://github.com/CleverCloud/biscuit/commit/ec99146e4689141a83478b3f50f1efdb3b1468b9
Rust: https://github.com/CleverCloud/biscuit-rust/commit/cd9495a2d59ab001d39b187c88a0f2ef2c918364

**Comment by Geal** [comment]
#62: Renaming "caveat" to "check", introduce "allow" and "deny" policies
#60: new syntax

spec: https://github.com/CleverCloud/biscuit/commit/fea8c3327f419fbe3ce21047e7b05b1b12ce0aa4
Rust: https://github.com/CleverCloud/biscuit-rust/commit/b4e2b0618607b90389f907b87c74a0c77dd361a4 and https://github.com/CleverCloud/biscuit-rust/commit/34107fcd5e2d3ca1a5e597994a08e45fa3ff6de0

**Comment by Geal** [comment]
With those changes, most of the work for 1.0 is done. now it needs a bit of polishing, like taking care of those issues:
https://github.com/CleverCloud/biscuit-rust/issues/29
https://github.com/CleverCloud/biscuit-rust/issues/30
https://github.com/CleverCloud/biscuit-rust/issues/31

and making sure the specification is clear enough on the 1.0 changes

**Comment by Geal** [comment]
adding #63 to the list, since I'm changing the syntax for those operations

**Comment by Geal** [comment]
#63: renaming In to Contains, removing NotIn
Rust: https://github.com/CleverCloud/biscuit-rust/commit/6b3f901c2b5b9442a4cfe91d89d102a176eb10c1
spec: https://github.com/CleverCloud/biscuit/commit/01ea43fa9bb09bfc93d6c26e66cd4ec16fd661cc

**Comment by Geal** [comment]
now would be a good time to think of other operations that could be supported. Right now I'm thinking of adding `.len()` for strings, sets and byte arrays

**Comment by Geal** [comment]
I added revocation identifiers for #1:
spec: bf3f7b2
Rust version: CleverCloud/biscuit-rust@451690c

**Comment by Geal** [comment]
more operations added to expressions:
spec https://github.com/CleverCloud/biscuit/commit/1c09f36934a1129ea358694f7712176692e5078b
Rust: https://github.com/CleverCloud/biscuit-rust/commit/ada0c950f48abafb25c58be1e34900a1c8c07490

**Comment by Geal** [comment]
the 1.0 release is done :partying_face:
